In [169]:
import pandas as pd
import numpy as np
from scipy import stats 
import plotly.express as px
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [170]:
df = pd.read_csv('wyniki.csv', names=['Gender', 'Grade'], skiprows=1)
df.head(3)

Gender  Grade
0      F      6
1      F      6
2      F     10

In [171]:
df.isnull().sum()

Gender    0
Grade     0
dtype: int64

In [172]:
df.groupby(df['Gender']).count()

Grade
Gender       
F         185
M         172

In [173]:
#For Female
mean_f = np.mean(df_f['Grade'])
std_error_f = np.std(df_f['Grade']) / np.sqrt(len(df_f['Grade']))
count_f = df_f['Gender'].count()

In [174]:
#Form Men
mean_m = np.mean(df_m['Grade'])
std_error_m = np.std(df_m['Grade']) / np.sqrt(len(df_m['Grade']))
count_m = df_m['Gender'].count()

In [175]:
alpha = 0.05
test_t = stats.ttest_ind_from_stats( 
                           df_m['Grade'].mean(), df_f['Grade'].mean(),
                           std_error_m, std_error_f,
                           count_m, count_f)

In [176]:
 significance_level = 0.05
 significance_level < test_t[1]
#parametr alpha is smaller than t-test
#Teur value give us information, that H1 is possible and H0 is False

True

In [177]:
#task 2

In [178]:
data = pd.read_csv('ZyskiFirmyX.csv', names=['Year', 'Income'], skiprows=1)

In [179]:
data.head(3)

Year  Income
0  1821    1645
1  1822     658
2  1823    1926

In [180]:
px.scatter(data, "Year", "Income", title="Income of company X per year")

In [181]:
#On plot we don't see any linear trend - data is scattered

In [182]:
Y=data['Income'].tolist()
X=data['Year'].tolist()

model = smf.ols('Income ~ Year', data=data).fit()
print(model.summary())
#R^2 = 0 and realtive low p-value give as information to accept H0

                            OLS Regression Results                            
Dep. Variable:                 Income   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                   0.09357
Date:                Sat, 28 Jan 2023   Prob (F-statistic):              0.760
Time:                        21:53:54   Log-Likelihood:                -1521.3
No. Observations:                 200   AIC:                             3047.
Df Residuals:                     198   BIC:                             3053.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1373.8795   1150.888      1.194      0.2

In [184]:
#task 3
data = pd.read_csv('spendingscores.csv')

In [185]:
data.sample(3)

Gender  Age  AnnualIncome  SpendingScore
65     Male   18            48             59
72   Female   60            50             49
152  Female   44            78             20

In [186]:
data.isna().sum()

Gender           0
Age              0
AnnualIncome     0
SpendingScore    0
dtype: int64

In [187]:
df = data
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [188]:
data['Male_true'] = (data['Gender'] == 'Male')

In [189]:
data['Female_true'] = (data['Gender'] == 'Female')

In [190]:
data_wg = data.drop(columns=['Gender'])

In [204]:
model = smf.ols('SpendingScore~Age+AnnualIncome+Male_true+Female_true', data=data_wg).fit()

In [205]:
print(f"Model 1 P Values:\n{model.pvalues.values}")
print(f"Model 1 Std Errs:\n{model.bse.values}")
print(f"Model 1 Coef:\n{model.params.values}")

Model 1 P Values:
[2.40458897e-22 2.56590205e-13 6.50522244e-18 3.05517724e-06
 9.05093933e-01]
Model 1 Std Errs:
[4.40385456 2.96620967 2.65801176 0.12491583 0.06641961]
Model 1 Coef:
[ 4.86156111e+01  2.33011887e+01  2.53144224e+01 -6.00371040e-01
  7.92939510e-03]


In [192]:
px.imshow(data.corr(), color_continuous_scale='Agsunset', title="Correlation heatmap of data")

In [193]:
infl = model.get_influence()
print(infl.summary_table())

       obs      endog     fitted     Cook's   student.   hat diag    dffits   ext.stud.     dffits
                           value          d   residual              internal   residual           
--------------------------------------------------------------------------------------------------
         0     39.000     60.629      0.007     -0.898      0.039     -0.182     -0.898     -0.182
         1     81.000     59.428      0.006      0.895      0.037      0.176      0.894      0.176
         2      6.000     62.049      0.035     -2.318      0.031     -0.417     -2.345     -0.422
         3     77.000     60.248      0.003      0.692      0.029      0.119      0.691      0.119
         4     40.000     55.453      0.002     -0.637      0.023     -0.099     -0.636     -0.098
         5     76.000     60.857      0.002      0.626      0.029      0.108      0.625      0.108
         6      6.000     53.060      0.017     -1.937      0.022     -0.288     -1.950     -0.290
         7

In [194]:
fig = px.scatter(data, x='Age', y='Gender')
fig.show()

#as we se, by two category corelation on level 0,5 is not neccesery 

In [206]:
model2 = smf.ols(formula="SpendingScore ~ Age+Male_true+Female_true", data=data).fit()

In [207]:
print(f"Model 2 P Values:\n{model2.pvalues.values}")
print(f"Model 2 Std Errs:\n{model2.bse.values}")
print(f"Model 2 Coef:\n{model2.params.values}")

Model 2 P Values:
[4.37138593e-32 7.88095614e-17 4.72509598e-22 2.85282740e-06]
Model 2 Std Errs:
[3.43820806 2.56926471 2.32916121 0.12458719]
Model 2 Coef:
[48.94284372 23.47681136 25.46603236 -0.60060795]
